### ISSUE TITLE
Find the shortest path among the mesh nodes 

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#107]
## I'm submitting a ...

  - [ ] feature request
  

## Expected Behavior

During text messaging among mesh nodes, the mesh hop should be reduced.

## Actual Behavior

Now, a text message is traversed through multiple mesh hops to reach the destination.

## What is the motivation / use case for changing the behavior?

Increase the performance of messaging

**Comment by W3-Tariqul** [comment]
Now mesh node has multiple paths to communicate a node. But each path has a separate hop count that indicates that how far the destination is. Now we've added to select the shortest path to reach the destination according to hop count.  The middle/ forwarder node will do the same thing for its next immediate node

**Comment by W3-Anjan** [comment]
feature done
