### ISSUE TITLE
WIFI permission not working perfectly on Android 10 devices

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#108]
## Description

On some of the android 10 devices, WIFI permission is not working

## Expected Behavior

For mesh creation WIFI is necessary 

## Actual Behavior

Now on Android version 10, the WIFI should perform well

## Possible Fix

Explore the codebase and take possible use cases to resolve the case

## Steps to Reproduce

1. Start telemesh on Android 10 device.
2. When Wifi permission arise, then it is not behaving perfectly

## Your Environment

* App version used: Android 10/ API level 29
* Device Name and version: Samsung Galaxy Note 10
* Operating System and version:

**Comment by W3-Aziz** [comment]
Google added some additional security patches for programmatically wifi connection. Without user acknowledgment, the application can,t connect with any wifi. 

We are working on these issues to find out the best way around for our Telemesh App to handle this issue.

**Comment by W3-Anjan** [comment]
this feature done
