### ISSUE TITLE
Enable content broadcast in telemesh

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#120]
## I'm submitting a ...

  - [x] feature request
  - [] support request

Telemesh users should be able to send multimedia content to each other.

**Comment by azizcse** [comment]
Content broadcast in mesh version-2 is under development

**Comment by W3-Aziz** [comment]
Content broadcast is a new upcoming feature in Telemesh. We are working on this feature.

**Comment by W3-Aziz** [comment]
The implementation of Content broadcast from Telemesh dashboard to Telemesh app local user in a specific region is done. The latest code also merged with master branch
