### ISSUE TITLE
update new KPI and analytics data to Telemesh dashboard

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#126]
## I'm submitting a ...

  - [*] feature request
  - [ ] support request

Update new KPI and analytics data to Telemesh dashboard

**Comment by W3-MajorArif** [comment]
Make a schedular for collecting group count data in the application

**Comment by W3-MajorArif** [comment]
Collecting group count data in parse server through API and update those data as synced in the application.
