### ISSUE TITLE
Prepare new wireframe for UI/UX

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#128]
## I'm submitting a ...

  - [*] feature request
  - [ ] support request

We will prepare a new wireframe for the UI/UX of the application and submit feedback for review to the stakeholders.

**Comment by W3-Ekram** [comment]
Hoping for a more simplified user experience including UI for the new features as well.

**Comment by W3-Anjan** [comment]
new wireframe design done and already implemeted
