### ISSUE TITLE
ERROR: Plugin [id: 'io.left.rightmesh.rightmesh-plugin', version: '1.8.4'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by Gakam** [w3-engineers/telemesh#23]
ERROR: Plugin [id: 'io.left.rightmesh.rightmesh-plugin', version: '1.8.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.left.rightmesh.rightmesh-plugin:io.left.rightmesh.rightmesh-plugin.gradle.plugin:1.8.4')
  Searched in the following repositories:
    Google
    BintrayJCenter
    MavenRepo
    maven(https://artifactory.rightmesh.io/artifactory/maven)
Open File

**Comment by W3-Mimo** [comment]
We are used RightMesh credential for local environment and CI environment. So this issue occurred in local side. Now we break down the whole process for getting credential and change credential retrieving pattern. And also set a priority for solving this issue.

Thanks.
