### ISSUE TITLE
Unable to start the daemon process.

### ISSUE THREAD

**Issue by Gakam** [w3-engineers/telemesh#24]
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.6/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap

**Comment by W3-Azim** [comment]
It should be fixed with #23. If it still exists after the closing of #23, this can be reopened.
