### ISSUE TITLE
Message receiving problem from Multiverse server 

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#54]
After buying internet from seller, message not received 
## Description

When internet is available on buyer end by token and start internet messaging then the message not delivered to other end.
## Expected Behavior

We need flawless messaging 
## Actual Behavior

Now local messaging is ok but have some problem on internet messaging

**Comment by W3-Anjan** [comment]
What is the current status of this ticket?

**Comment by W3-Mimo** [comment]
Multiverse message receive problem resolved and it works properly as per our system. 
Thanks.
