### ISSUE TITLE
Android Notification is not working on Samsung api level 9 on Telemesh

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#56]
Notification is not working on Samsung api level 9
## Description

Android system's notification should be ok for all version and on all devices

## Context

This is a major concern because latest android api is not working on Telemesh code

## Your Environment

* App version used: 0.2.2
* Device Name and version: Samsung M20 , Android Pie
* Operating System and version: OS 9.0

**Comment by W3-Tariqul** [comment]
- After a long process i found that when we send parcelable data like userModel class android os clear all intent value.
		May be the reason is memory savings. so we have to do
		1. Send user id via intent
		2. Get user model from DB by id

**Comment by W3-Tariqul** [comment]
Now notification holding only user id and its related message will show when chatting page open
