### ISSUE TITLE
Separate Viper module from App and create AAR file

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/telemesh#57]
## I'm submitting a ...

  - [x] feature request
  - [ ] support request

## Expected Behavior

Viper module is used to provide set of api through which application layer communicates with communication layer. It should be added via gradle dependency 

## What is the motivation / use case for changing the behavior?

Now a day's most of the popular library introduce gradle dependency and it's the standard way of adding support library on android studio.

**Comment by W3-Mimo** [comment]
Hello
Initially upload all new files in app modules and also upload the viper modules file that consists AIDL service for communicating with mesh layer and connecting with app module for passing data.

**Comment by W3-Mimo** [comment]
Hello, 
Now separately exposed viper as a open source project and also made a .ARR file to use in gradle. 
Thanks.
