### ISSUE TITLE
BROADCAST_URL not found 

### ISSUE THREAD

**Issue by faysal-cse** [w3-engineers/telemesh#82]
![Screen Shot 2019-12-03 at 12 34 18 PM](https://user-images.githubusercontent.com/21218893/70026256-85770100-15c9-11ea-9b53-76e96394d5fa.png)

## Description
At first clone the project and Android Studio trying to sync then I saw this issue. 

## Expected Behavior
Sync the project successfully 

## Steps to Reproduce

1. Clone project from Github
2. Open project with Android Studio

## Context
Trying to build TeleMesh project

## Your Environment

* App version used: 
* Device Name and version: Huawei Nova 3i (9.0)
* Operating System and version: Mac OS X 10.14.5, Android Studio (3.5.1)

**Comment by W3-Anjan** [comment]
Thanks, @faysal-cse for raising your problem.
You are facing this issue because you need to provide valid credentials to successfully build the Telemesh app.
You will get the required credentials to build successfully.
Thanks again and be stay with us.
